# Generated by Django 5.1.1 on 2024-12-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_messagereadstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
