# Generated by Django 5.1 on 2024-10-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Signifies if a user is active on the platform.', verbose_name='active status'),
        ),
    ]
