# Generated by Django 5.1 on 2024-10-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.DeleteModel(
            name='MembershipStatus',
        ),
    ]
