# Generated by Django 5.1.1 on 2024-11-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_status_delete_membershipstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pictures/'),
        ),
    ]
