# Generated by Django 5.1.1 on 2024-12-26 03:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/banner_images/', validators=[accounts.models.validate_image_file_type, accounts.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pictures/', validators=[accounts.models.validate_image_file_type, accounts.models.validate_image_file_size]),
        ),
    ]
