# Generated by Django 5.1.1 on 2024-12-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='invite_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='member_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
