# Generated by Django 5.1.1 on 2025-01-03 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('action_stage', models.CharField(choices=[('someday', 'Someday'), ('backlog', 'Backlog'), ('progress', 'In Progress'), ('review', 'In Review'), ('complete', 'Complete'), ('archived', 'Archived')], max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.projectmembership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.projectmembership')),
            ],
        ),
    ]
