# Generated by Django 5.1.1 on 2025-01-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_nextaction_teammembernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextaction',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='teammembernote',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
