# Generated by Django 5.1.1 on 2025-01-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_nextaction_notes_alter_teammembernote_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextaction',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
