# Generated by Django 5.1.1 on 2025-01-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_nextaction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembernote',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
